#ifndef __hvac_msgs__srv__SetAc_Request__idl 
#define __hvac_msgs__srv__SetAc_Request__idl 
 
 
module hvac_msgs { module srv { 

const string TOPIC_SET_AC = "hvac_msgs/srv/SetAc";

/**
 * 空调Ac开关
 */
struct SetAcRequest { 
    boolean on; 
    long zone;//@key
}; 

#pragma keylist SetAcRequest zone 
 
}; };  // module srv::hvac_msgs
 
#endif  // __hvac_msgs__srv__SetAc_Request__idl
