
#ifndef __hvac_msgs__srv__SetTemperature_Request__idl 
#define __hvac_msgs__srv__SetTemperature_Request__idl 
 
 
module hvac_msgs { module srv { 

const string TOPIC_HVAC_SET_TEMPERATURE = "hvac_msgs/srv/SetTemperature";

 
}; };  // module hvac_msgs::srv
 
#endif  // __hvac_msgs__srv__SetTemperature_Request__idl
