#!/bin/bash

BUILD_TYPE=Debug
BUILD_DIR="build"
INSTALL_DIR="/usr/local"

rm -rf "${BUILD_DIR}"

cmake -B "${BUILD_DIR}" \
    -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
    -DCPACK_OUTPUT_FILE_PREFIX="${INSTALL_DIR}"

echo "000"
cmake --build "${BUILD_DIR}"

cd ${BUILD_DIR}

# make  test CTEST_OUTPUT_ON_FAILURE=TRUE GTEST_COLOR=TRUE

sudo make install

# sudo make package
