#ifndef __hvac_msgs__srv__SetPower_Request__idl 
#define __hvac_msgs__srv__SetPower_Request__idl 
 
 
module hvac_msgs { module srv { 
 
/**
 * 空调总开关
 */
struct SetPowerRequest { 
    boolean on; 
    long zone;
}; 
 
}; };  // module hvac_msgs::srv
 
#endif  // __hvac_msgs__srv__SetPower_Request__idl
