#ifndef __hvac_msgs__srv__SetRecirc_Request__idl 
#define __hvac_msgs__srv__SetRecirc_Request__idl 
 
 
module hvac_msgs { module srv { 
 
/**
 * 车内空气循环开关
 */
struct SetRecircRequest { 
    boolean on; 
    long zone;
}; 
 
}; };  // module hvac_msgs::srv
 
#endif  // __hvac_msgs__srv__SetRecirc_Request__idl
