/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: HvacSrv.idl
  Source: HvacSrv.hpp
  Cyclone DDS: v0.10.0

*****************************************************************/
#ifndef DDSCXX_HVACSRV_HPP
#define DDSCXX_HVACSRV_HPP

#include <string>

namespace hvac_msgs
{
namespace srv
{
const std::string TOPIC_SET_STEERING_WHEEL_HEAT = "hvac_msgs/srv/STEERING_WHEEL_HEAT";

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

}
}


namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_HVACSRV_HPP
