/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: SetTemperature.idl
  Source: SetTemperature.hpp
  Cyclone DDS: v0.10.0

*****************************************************************/
#ifndef DDSCXX_SETTEMPERATURE_HPP
#define DDSCXX_SETTEMPERATURE_HPP

#include <string>

namespace hvac_msgs
{
namespace srv
{
const std::string TOPIC_HVAC_SET_TEMPERATURE = "hvac_msgs/srv/SetTemperature";

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

}
}


namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_SETTEMPERATURE_HPP
