/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: Cabin.idl
  Source: Cabin.cpp
  Cyclone DDS: v0.10.0

*****************************************************************/
#include "Cabin.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

