/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: Cabin.idl
  Source: Cabin.hpp
  Cyclone DDS: v0.10.0

*****************************************************************/
#ifndef DDSCXX_CABIN_HPP
#define DDSCXX_CABIN_HPP

#include <string>

namespace cabin_msgs
{
namespace msg
{
const std::string TOPIC_CABIN_TEMPERATURE = "cabin_msgs/msg/Temperature";

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

}
}


namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_CABIN_HPP
