/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: SeatSrv.idl
  Source: /home/an/workspace/dds/dds-samples/data-types-cyclonedds/buildandroid/seat_msgs/srv/SeatSrv.cpp
  Cyclone DDS: v0.10.0

*****************************************************************/
#include "/home/an/workspace/dds/dds-samples/data-types-cyclonedds/buildandroid/seat_msgs/srv/SeatSrv.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

