/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: SeatSrv.idl
  Source: SeatSrv.cpp
  Cyclone DDS: v0.10.0

*****************************************************************/
#include "SeatSrv.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

