/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: Prepare.idl
  Source: /home/an/workspace/dds/dds-samples/data-types-cyclonedds/buildandroid/battery_msgs/srv/Prepare.hpp
  Cyclone DDS: v0.10.0

*****************************************************************/
#ifndef DDSCXX__HOME_AN_WORKSPACE_DDS_DDS_SAMPLES_DATA_TYPES_CYCLONEDDS_BUILDANDROID_BATTERY_MSGS_SRV_PREPARE_HPP
#define DDSCXX__HOME_AN_WORKSPACE_DDS_DDS_SAMPLES_DATA_TYPES_CYCLONEDDS_BUILDANDROID_BATTERY_MSGS_SRV_PREPARE_HPP

#include <cstdint>

namespace battery_msgs
{
namespace srv
{
class PrepareRequest
{
private:
 int32_t timepoint_ = 0;

public:
  PrepareRequest() = default;

  explicit PrepareRequest(
    int32_t timepoint) :
    timepoint_(timepoint) { }

  int32_t timepoint() const { return this->timepoint_; }
  int32_t& timepoint() { return this->timepoint_; }
  void timepoint(int32_t _val_) { this->timepoint_ = _val_; }

  bool operator==(const PrepareRequest& _other) const
  {
    (void) _other;
    return timepoint_ == _other.timepoint_;
  }

  bool operator!=(const PrepareRequest& _other) const
  {
    return !(*this == _other);
  }

};

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::battery_msgs::srv::PrepareRequest>::getTypeName()
{
  return "battery_msgs::srv::PrepareRequest";
}

template <> constexpr bool TopicTraits<::battery_msgs::srv::PrepareRequest>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::battery_msgs::srv::PrepareRequest>::type_map_blob_sz() { return 218; }
template<> constexpr unsigned int TopicTraits<::battery_msgs::srv::PrepareRequest>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::battery_msgs::srv::PrepareRequest>::type_map_blob() {
  static const uint8_t blob[] = {
 0x3b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x6f,  0xed,  0x66,  0x29,  0x83,  0xe1,  0x4e, 
 0x59,  0xf5,  0xca,  0xd5,  0x1e,  0x10,  0xcf,  0x00,  0x23,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x86,  0x2e,  0xe3,  0xe2,  0x00, 
 0x70,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xa1,  0x29,  0xf9,  0x5a,  0xb3,  0x55,  0x05, 
 0x4f,  0xcc,  0x46,  0x87,  0xfb,  0xf5,  0x04,  0x00,  0x58,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x62,  0x61,  0x74,  0x74, 
 0x65,  0x72,  0x79,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x73,  0x72,  0x76,  0x3a,  0x3a,  0x50, 
 0x72,  0x65,  0x70,  0x61,  0x72,  0x65,  0x52,  0x65,  0x71,  0x75,  0x65,  0x73,  0x74,  0x00,  0x00,  0x00, 
 0x20,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x04,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x74,  0x69,  0x6d,  0x65,  0x70,  0x6f,  0x69,  0x6e, 
 0x74,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xa1,  0x29,  0xf9, 
 0x5a,  0xb3,  0x55,  0x05,  0x4f,  0xcc,  0x46,  0x87,  0xfb,  0xf5,  0x04,  0xf1,  0x6f,  0xed,  0x66,  0x29, 
 0x83,  0xe1,  0x4e,  0x59,  0xf5,  0xca,  0xd5,  0x1e,  0x10,  0xcf, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::battery_msgs::srv::PrepareRequest>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x6f,  0xed,  0x66,  0x29,  0x83,  0xe1,  0x4e,  0x59,  0xf5,  0xca,  0xd5, 
 0x1e,  0x10,  0xcf,  0x00,  0x27,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xa1,  0x29,  0xf9,  0x5a,  0xb3,  0x55,  0x05,  0x4f,  0xcc,  0x46,  0x87, 
 0xfb,  0xf5,  0x04,  0x00,  0x5c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::battery_msgs::srv::PrepareRequest>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::battery_msgs::srv::PrepareRequest>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::battery_msgs::srv::PrepareRequest)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::battery_msgs::srv::PrepareRequest>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::battery_msgs::srv::PrepareRequest& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.timepoint()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::battery_msgs::srv::PrepareRequest& instance, bool as_key) {
  auto &props = get_type_props<::battery_msgs::srv::PrepareRequest>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::battery_msgs::srv::PrepareRequest& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.timepoint()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::battery_msgs::srv::PrepareRequest& instance, bool as_key) {
  auto &props = get_type_props<::battery_msgs::srv::PrepareRequest>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::battery_msgs::srv::PrepareRequest& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.timepoint()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::battery_msgs::srv::PrepareRequest& instance, bool as_key) {
  auto &props = get_type_props<::battery_msgs::srv::PrepareRequest>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::battery_msgs::srv::PrepareRequest& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.timepoint()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::battery_msgs::srv::PrepareRequest& instance, bool as_key) {
  auto &props = get_type_props<::battery_msgs::srv::PrepareRequest>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX__HOME_AN_WORKSPACE_DDS_DDS_SAMPLES_DATA_TYPES_CYCLONEDDS_BUILDANDROID_BATTERY_MSGS_SRV_PREPARE_HPP
